/**
 * @file libs/better-auth-utilities/src/index.ts
 * @description Public API for the better-auth-utilities library.
 */

export {
	createAuthServer,
	createClientConfig,
	createServerConfig,
	defineConfig,
	createAuthClient,
	AdminModule,
	APIKeyModule,
	BearerModule,
	EmailOTPModule,
	GenericOAuthModule,
	JWTModule,
	OrganizationModule,
	TwoFactorModule,
	UsernameModule,
	AdminService,
	APIKeyService,
	BearerService,
	EmailOTPService,
	GenericOAuthService,
	JWTService,
	OrganizationService,
	TwoFactorService,
	UsernameService,
} from './lib/better-auth-utilities.js';

export type {
	AdapterContext,
	AdapterResponse,
	AuthProvider,
	AvailablePlugins,
	BetterAuthConfig,
	ClientConfig,
	DEFAULT_CLIENT_CONFIG,
	DEFAULT_SERVER_CONFIG,
	InferAuthClient,
	AuthClient,
	AuthClientOf,
	AuthClientApiOf,
	AuthClientApiEndpointKeyOf,
	AuthClientApiEndpointOf,
	AuthClientApiEndpointParametersOf,
	AuthClientApiEndpointFirstParameter,
	AuthClientApiEndpointArgsOf,
	AuthClientSessionOf,
	AuthClientSessionUserSessionOf,
	AuthClientSessionUserOf,
	AuthServerOf,
	ServerConfig,
	User,
} from './lib/better-auth-utilities.ts';
